version: '3'
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_PORT=12345
      - SERVER_LISTEN_BACKLOG=7
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:
      - "./config/server:/config"

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_SERVER_ADDRESS=server:12345
      - CLI_FIRST_NAME=Martin
      - CLI_LAST_NAME=Perez
      - CLI_DOCUMENT=12345678
      - CLI_BIRTH_DATE=1995-06-23
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - "./config/client:/config"

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24